import type { Brand, Campaign, Mission, Reward, User, Venue, VenueMembership } from "./types";

const now = new Date();
const iso = (d: Date) => d.toISOString();
const addDays = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + n);
  return iso(d);
};

export const seedUsers: User[] = [
  {
    id: "u_demo",
    fullName: "Demo Participante",
    docType: "CC",
    docNumber: "1000000000",
    email: "demo@kicker.com",
    phone: "+57 300 000 0000",
    city: "Barranquilla",
    profileKind: "bartender",
    roles: ["participant"],
    verification: "verified",
    active: true,
    createdAt: iso(now),
  },
  {
    id: "u_ana",
    fullName: "Ana Torres",
    docType: "CC",
    docNumber: "1010101010",
    email: "ana@kicker.com",
    phone: "+57 301 111 1111",
    city: "Barranquilla",
    profileKind: "waiter",
    roles: ["participant"],
    verification: "verified",
    active: true,
    createdAt: iso(now),
  },
  {
    id: "u_luis",
    fullName: "Luis Pérez",
    docType: "CC",
    docNumber: "1020202020",
    email: "luis@kicker.com",
    phone: "+57 302 222 2222",
    city: "Cartagena",
    profileKind: "seller",
    roles: ["participant"],
    verification: "pending",
    active: true,
    createdAt: iso(now),
  },
  {
    id: "u_mar",
    fullName: "Marcela Ríos",
    docType: "CC",
    docNumber: "1030303030",
    email: "marcela@kicker.com",
    phone: "+57 303 333 3333",
    city: "Santa Marta",
    profileKind: "promoter",
    roles: ["participant"],
    verification: "verified",
    active: true,
    createdAt: iso(now),
  },
  {
    id: "u_juan",
    fullName: "Juan Ospina",
    docType: "CC",
    docNumber: "1040404040",
    email: "juan@kicker.com",
    phone: "+57 304 444 4444",
    city: "Barranquilla",
    profileKind: "shopkeeper",
    roles: ["participant"],
    verification: "verified",
    active: true,
    createdAt: iso(now),
  },
  {
    id: "u_venueadmin",
    fullName: "Carlos Admin",
    docType: "CC",
    docNumber: "2000000000",
    email: "venue@kicker.com",
    phone: "+57 310 000 0000",
    city: "Barranquilla",
    profileKind: "venue_admin",
    roles: ["venue_admin"],
    verification: "verified",
    active: true,
    createdAt: iso(now),
  },
  {
    id: "u_buena_vida_admin",
    fullName: "Operador Buena Vida",
    docType: "CC",
    docNumber: "2000000001",
    email: "buena.vida@kicker.com",
    phone: "+57 310 000 0001",
    city: "Cartagena",
    profileKind: "venue_admin",
    roles: ["venue_admin"],
    verification: "verified",
    active: true,
    createdAt: iso(now),
    merchantIds: ["ctg_buena_vida"],
  },
  {
    id: "u_auditor",
    fullName: "Sofía Auditora",
    docType: "CC",
    docNumber: "3000000000",
    email: "auditor@kicker.com",
    phone: "+57 320 000 0000",
    city: "Bogotá",
    profileKind: "customer_service",
    roles: ["auditor"],
    verification: "verified",
    active: true,
    createdAt: iso(now),
  },
  {
    id: "u_admin",
    fullName: "Admin Kicker",
    docType: "CC",
    docNumber: "4000000000",
    email: "admin@kicker.com",
    phone: "+57 330 000 0000",
    city: "Bogotá",
    profileKind: "customer_service",
    roles: ["platform_admin"],
    verification: "verified",
    active: true,
    createdAt: iso(now),
  },
];

export const seedVenues: Venue[] = [
  {
    id: "v_caribe",
    commercialName: "Restaurante Caribe",
    legalName: "Caribe SAS",
    nit: "900111222-1",
    type: "restaurant",
    city: "Barranquilla",
    address: "Cra 53 #80-20",
    lat: 10.996,
    lng: -74.807,
    adminUserId: "u_venueadmin",
    active: true,
    joinCode: "CARIBE-01",
  },
  {
    id: "v_central",
    commercialName: "Bar Central",
    legalName: "Central Bar SAS",
    nit: "900111222-2",
    type: "bar",
    city: "Barranquilla",
    address: "Cll 84 #45-10",
    lat: 11.005,
    lng: -74.812,
    adminUserId: "u_venueadmin",
    active: true,
    joinCode: "CENTRAL-02",
  },
  {
    id: "v_bahia",
    commercialName: "Hotel Bahía",
    legalName: "Bahía Hoteles SAS",
    nit: "900111222-3",
    type: "hotel",
    city: "Cartagena",
    address: "Av Santander #12-05",
    lat: 10.423,
    lng: -75.549,
    active: true,
    joinCode: "BAHIA-03",
  },
  {
    id: "v_norte",
    commercialName: "Licorera Norte",
    legalName: "Licores del Norte SAS",
    nit: "900111222-4",
    type: "liquor_store",
    city: "Barranquilla",
    address: "Cra 51B #79-100",
    lat: 10.998,
    lng: -74.81,
    active: true,
    joinCode: "NORTE-04",
  },
  {
    id: "v_plaza",
    commercialName: "Café Plaza",
    legalName: "Plaza Café SAS",
    nit: "900111222-5",
    type: "cafe",
    city: "Santa Marta",
    address: "Cll 22 #3-40",
    lat: 11.241,
    lng: -74.211,
    active: true,
    joinCode: "PLAZA-05",
  },
];

export const seedBrands: Brand[] = [
  { id: "b_astutto", name: "Astutto" },
  { id: "b_maranta", name: "Maranta" },
  { id: "b_patrimonio", name: "Patrimonio de Familia" },
];

export const seedMemberships: VenueMembership[] = [
  {
    id: "m_demo_caribe",
    userId: "u_demo",
    venueId: "v_caribe",
    status: "approved",
    requestedAt: iso(now),
    decidedAt: iso(now),
  },
  {
    id: "m_demo_central",
    userId: "u_demo",
    venueId: "v_central",
    status: "approved",
    requestedAt: iso(now),
    decidedAt: iso(now),
  },
  {
    id: "m_ana_caribe",
    userId: "u_ana",
    venueId: "v_caribe",
    status: "approved",
    requestedAt: iso(now),
    decidedAt: iso(now),
  },
  {
    id: "m_juan_norte",
    userId: "u_juan",
    venueId: "v_norte",
    status: "approved",
    requestedAt: iso(now),
    decidedAt: iso(now),
  },
  {
    id: "m_mar_plaza",
    userId: "u_mar",
    venueId: "v_plaza",
    status: "pending",
    requestedAt: iso(now),
  },
];

export const seedCampaigns: Campaign[] = [
  {
    id: "c_astutto",
    name: "Impulso Astutto",
    brandId: "b_astutto",
    description: "Impulsa las ventas de ginebra Astutto en tu establecimiento.",
    startDate: addDays(-5),
    endDate: addDays(25),
    budgetPoints: 100000,
    status: "published",
    targetCities: ["Barranquilla", "Cartagena", "Santa Marta"],
    targetVenueIds: ["v_caribe", "v_central", "v_bahia", "v_norte"],
    targetProfileKinds: ["bartender", "waiter", "seller", "shopkeeper"],
    ownerUserId: "u_admin",
    terms: "Aplica solo para ventas verificadas mediante factura.",
  },
  {
    id: "c_maranta",
    name: "Visibilidad Maranta",
    brandId: "b_maranta",
    description: "Ubica material promocional Maranta en la barra principal.",
    startDate: addDays(-2),
    endDate: addDays(20),
    budgetPoints: 60000,
    status: "published",
    targetCities: ["Barranquilla", "Santa Marta"],
    targetVenueIds: ["v_caribe", "v_central", "v_plaza"],
    targetProfileKinds: ["bartender", "promoter", "merchandiser"],
    ownerUserId: "u_admin",
    terms: "Foto clara del material instalado.",
  },
  {
    id: "c_patrimonio",
    name: "Conoce Patrimonio",
    brandId: "b_patrimonio",
    description: "Capacítate en Patrimonio de Familia y aprueba el cuestionario.",
    startDate: addDays(-10),
    endDate: addDays(30),
    budgetPoints: 40000,
    status: "published",
    targetCities: ["Barranquilla", "Cartagena", "Santa Marta", "Bogotá"],
    targetVenueIds: ["v_caribe", "v_central", "v_bahia", "v_norte", "v_plaza"],
    targetProfileKinds: [
      "waiter",
      "bartender",
      "seller",
      "promoter",
      "brand_ambassador",
      "shopkeeper",
    ],
    ownerUserId: "u_admin",
    terms: "Calificación mínima 80%.",
  },
];

export const seedMissions: Mission[] = [
  {
    id: "mi_astutto_sell",
    campaignId: "c_astutto",
    name: "Vende 5 unidades de ginebra Astutto",
    description: "Impulsa la venta de Astutto durante tu turno.",
    instructions:
      "Ofrece Astutto a los clientes, registra las unidades vendidas y adjunta la factura.",
    type: "sale",
    startDate: addDays(-5),
    endDate: addDays(25),
    rewardPoints: 500,
    totalQuota: 100,
    perUserQuota: 3,
    frequency: "weekly",
    requiresGeo: true,
    requiresPhoto: true,
    requiresVenueValidation: false,
    requiresAudit: true,
    targetProfileKinds: ["bartender", "waiter", "seller"],
    targetVenueIds: ["v_caribe", "v_central", "v_bahia", "v_norte"],
    targetCities: ["Barranquilla", "Cartagena"],
    status: "active",
    geoRadiusMeters: 300,
    fields: [
      {
        id: "f1",
        label: "Unidades vendidas",
        type: "number",
        required: true,
        order: 1,
        min: 5,
      },
      {
        id: "f2",
        label: "Número de factura",
        type: "short_text",
        required: true,
        order: 2,
      },
      {
        id: "f3",
        label: "Fotografía de la factura",
        type: "photo",
        required: true,
        order: 3,
        maxFiles: 2,
      },
    ],
  },
  {
    id: "mi_maranta_display",
    campaignId: "c_maranta",
    name: "Ubica material Maranta en la barra",
    description: "Instala el afiche y habladores Maranta en un lugar visible.",
    instructions:
      "Coloca el material en la barra principal, tómale una foto y describe la ubicación.",
    type: "display",
    startDate: addDays(-2),
    endDate: addDays(20),
    rewardPoints: 300,
    totalQuota: 50,
    perUserQuota: 1,
    frequency: "campaign",
    requiresGeo: true,
    requiresPhoto: true,
    requiresVenueValidation: true,
    requiresAudit: true,
    targetProfileKinds: ["bartender", "promoter", "merchandiser"],
    targetVenueIds: ["v_caribe", "v_central", "v_plaza"],
    targetCities: ["Barranquilla", "Santa Marta"],
    status: "active",
    geoRadiusMeters: 300,
    fields: [
      {
        id: "f1",
        label: "Ubicación del material",
        type: "long_text",
        required: true,
        order: 1,
      },
      {
        id: "f2",
        label: "Fotografía del material instalado",
        type: "photo",
        required: true,
        order: 2,
      },
    ],
  },
  {
    id: "mi_patrimonio_training",
    campaignId: "c_patrimonio",
    name: "Capacitación Patrimonio de Familia",
    description: "Completa la capacitación y responde correctamente el cuestionario.",
    instructions: "Lee las instrucciones y responde el cuestionario.",
    type: "training",
    startDate: addDays(-10),
    endDate: addDays(30),
    rewardPoints: 200,
    totalQuota: 500,
    perUserQuota: 1,
    frequency: "once",
    requiresGeo: false,
    requiresPhoto: false,
    requiresVenueValidation: false,
    requiresAudit: true,
    targetProfileKinds: [
      "waiter",
      "bartender",
      "seller",
      "promoter",
      "brand_ambassador",
      "shopkeeper",
    ],
    targetVenueIds: ["v_caribe", "v_central", "v_bahia", "v_norte", "v_plaza"],
    targetCities: ["Barranquilla", "Cartagena", "Santa Marta", "Bogotá"],
    status: "active",
    fields: [
      {
        id: "q1",
        label: "¿Cuál es el origen principal de Patrimonio?",
        type: "single_choice",
        required: true,
        order: 1,
        options: ["Nacional", "Importado", "Regional"],
      },
      {
        id: "q2",
        label: "¿Con qué maridaje se recomienda?",
        type: "multi_choice",
        required: true,
        order: 2,
        options: ["Carnes", "Postres", "Quesos", "Pescados"],
      },
      {
        id: "q3",
        label: "Describe una recomendación al cliente",
        type: "long_text",
        required: true,
        order: 3,
      },
    ],
  },
];

export const seedRewards: Reward[] = [
  {
    id: "r_ctg_buena_vida",
    name: "Bono gastronómico $50.000",
    description: "Úsalo como parte de pago en alimentos y bebidas.",
    pointsRequired: 1000,
    stock: 25,
    active: true,
    merchantName: "Buena Vida Marisquería y Rooftop",
    city: "Cartagena",
    tripadvisorRank: 1,
    tripadvisorRating: 4.9,
    category: "Caribeña · Mariscos",
    merchantId: "ctg_buena_vida",
  },
  {
    id: "r_ctg_pezetarian",
    name: "Menú Pezetarian",
    description: "Bono para un bowl, sushi o plato seleccionado.",
    pointsRequired: 700,
    stock: 30,
    active: true,
    merchantName: "Pezetarian",
    city: "Cartagena",
    tripadvisorRank: 2,
    tripadvisorRating: 4.8,
    category: "Mariscos · Sushi",
    merchantId: "ctg_pezetarian",
  },
  {
    id: "r_ctg_7_cielos",
    name: "Experiencia rooftop $60.000",
    description: "Bono de consumo para alimentos o coctelería seleccionada.",
    pointsRequired: 1200,
    stock: 20,
    active: true,
    merchantName: "7 Cielos Rooftop",
    city: "Cartagena",
    tripadvisorRank: 3,
    tripadvisorRating: 4.9,
    category: "Caribeña · Peruana",
    merchantId: "ctg_7_cielos",
  },
  {
    id: "r_ctg_cande",
    name: "Almuerzo cartagenero",
    description: "Bono para un plato fuerte seleccionado de cocina local.",
    pointsRequired: 900,
    stock: 25,
    active: true,
    merchantName: "Restaurante Candé",
    city: "Cartagena",
    tripadvisorRank: 4,
    tripadvisorRating: 4.6,
    category: "Caribeña · Latina",
    merchantId: "ctg_cande",
  },
  {
    id: "r_ctg_ana",
    name: "Bono gastronómico $70.000",
    description: "Úsalo como parte de pago en la experiencia gastronómica.",
    pointsRequired: 1400,
    stock: 15,
    active: true,
    merchantName: "Ana Restaurante Bar",
    city: "Cartagena",
    tripadvisorRank: 5,
    tripadvisorRating: 4.9,
    category: "Caribeña · Mariscos",
    merchantId: "ctg_ana",
  },
  {
    id: "r_ctg_mar_antillas",
    name: "Cena caribeña $50.000",
    description: "Bono de consumo para platos y bebidas seleccionadas.",
    pointsRequired: 1000,
    stock: 30,
    active: true,
    merchantName: "Mar de las Antillas",
    city: "Cartagena",
    tripadvisorRank: 6,
    tripadvisorRating: 4.9,
    category: "Caribeña · Latina",
    merchantId: "ctg_mar_antillas",
  },
  {
    id: "r_ctg_verona",
    name: "Bono italiano $45.000",
    description: "Válido en pizzas, pastas o platos seleccionados.",
    pointsRequired: 900,
    stock: 25,
    active: true,
    merchantName: "Verona Restaurante",
    city: "Cartagena",
    tripadvisorRank: 7,
    tripadvisorRating: 4.8,
    category: "Italiana · Peruana",
    merchantId: "ctg_verona",
  },
  {
    id: "r_ctg_baroca",
    name: "Bono rooftop $60.000",
    description: "Bono de consumo para alimentos o bebidas seleccionadas.",
    pointsRequired: 1200,
    stock: 20,
    active: true,
    merchantName: "Baroca Rooftop",
    city: "Cartagena",
    tripadvisorRank: 8,
    tripadvisorRating: 4.9,
    category: "Caribeña · Latina",
    merchantId: "ctg_baroca",
  },
  {
    id: "r_ctg_marea",
    name: "Bono gastronómico $75.000",
    description: "Úsalo como parte de pago en platos seleccionados.",
    pointsRequired: 1500,
    stock: 15,
    active: true,
    merchantName: "Restaurante Marea",
    city: "Cartagena",
    tripadvisorRank: 9,
    tripadvisorRating: 4.5,
    category: "Caribeña · Latina",
    merchantId: "ctg_marea",
  },
  {
    id: "r_ctg_epoca",
    name: "Desayuno o brunch",
    description: "Bono para una opción de desayuno o brunch seleccionada.",
    pointsRequired: 650,
    stock: 35,
    active: true,
    merchantName: "Época Café Bar",
    city: "Cartagena",
    tripadvisorRank: 10,
    tripadvisorRating: 4.9,
    category: "Latina · Café",
    merchantId: "ctg_epoca",
  },
  {
    id: "r_bono50",
    name: "Bono de recarga $50.000",
    description: "Bono para recarga de celular.",
    pointsRequired: 1500,
    stock: 20,
    active: true,
  },
  {
    id: "r_kit",
    name: "Kit bartender Kicker",
    description: "Kit con coctelera, jigger y cucharilla.",
    pointsRequired: 3500,
    stock: 10,
    active: true,
  },
  {
    id: "r_camiseta",
    name: "Camiseta Kicker",
    description: "Camiseta oficial edición limitada.",
    pointsRequired: 800,
    stock: 50,
    active: true,
  },
];
