/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminExecutionsRouteImport } from './routes/admin.executions'
import { Route as AdminMissionsRouteImport } from './routes/admin.missions'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminRedemptionsRouteImport } from './routes/admin.redemptions'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminVenuesRouteImport } from './routes/admin.venues'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppMissionsRouteImport } from './routes/app.missions'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppRewardsRouteImport } from './routes/app.rewards'
import { Route as AppVenuesRouteImport } from './routes/app.venues'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AdminExecutionsIndexRouteImport } from './routes/admin.executions.index'
import { Route as AdminExecutionsIdRouteImport } from './routes/admin.executions.$id'
import { Route as AdminMissionsIndexRouteImport } from './routes/admin.missions.index'
import { Route as AdminMissionsIdRouteImport } from './routes/admin.missions.$id'
import { Route as AppMissionsIndexRouteImport } from './routes/app.missions.index'
import { Route as AppMissionsIdRouteImport } from './routes/app.missions.$id'
import { Route as AppMissionsIdExecuteRouteImport } from './routes/app.missions_.$id.execute'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExecutionsRoute = AdminExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionsRoute = AdminMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedemptionsRoute = AdminRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppVenuesRoute = AppVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AdminExecutionsIndexRoute = AdminExecutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminExecutionsRoute,
} as any)
const AdminExecutionsIdRoute = AdminExecutionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminExecutionsRoute,
} as any)
const AdminMissionsIndexRoute = AdminMissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMissionsRoute,
} as any)
const AdminMissionsIdRoute = AdminMissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMissionsRoute,
} as any)
const AppMissionsIndexRoute = AppMissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMissionsRoute,
} as any)
const AppMissionsIdRoute = AppMissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMissionsRoute,
} as any)
const AppMissionsIdExecuteRoute = AppMissionsIdExecuteRouteImport.update({
  id: '/missions_/$id/execute',
  path: '/missions/$id/execute',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/executions': typeof AdminExecutionsRouteWithChildren
  '/admin/missions': typeof AdminMissionsRouteWithChildren
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/app/activity': typeof AppActivityRoute
  '/app/missions': typeof AppMissionsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/rewards': typeof AppRewardsRoute
  '/app/venues': typeof AppVenuesRoute
  '/app/wallet': typeof AppWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/executions/$id': typeof AdminExecutionsIdRoute
  '/admin/missions/$id': typeof AdminMissionsIdRoute
  '/app/missions/$id': typeof AppMissionsIdRoute
  '/admin/executions/': typeof AdminExecutionsIndexRoute
  '/admin/missions/': typeof AdminMissionsIndexRoute
  '/app/missions/': typeof AppMissionsIndexRoute
  '/app/missions/$id/execute': typeof AppMissionsIdExecuteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/app/activity': typeof AppActivityRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rewards': typeof AppRewardsRoute
  '/app/venues': typeof AppVenuesRoute
  '/app/wallet': typeof AppWalletRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/executions/$id': typeof AdminExecutionsIdRoute
  '/admin/missions/$id': typeof AdminMissionsIdRoute
  '/app/missions/$id': typeof AppMissionsIdRoute
  '/admin/executions': typeof AdminExecutionsIndexRoute
  '/admin/missions': typeof AdminMissionsIndexRoute
  '/app/missions': typeof AppMissionsIndexRoute
  '/app/missions/$id/execute': typeof AppMissionsIdExecuteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/executions': typeof AdminExecutionsRouteWithChildren
  '/admin/missions': typeof AdminMissionsRouteWithChildren
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/app/activity': typeof AppActivityRoute
  '/app/missions': typeof AppMissionsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/rewards': typeof AppRewardsRoute
  '/app/venues': typeof AppVenuesRoute
  '/app/wallet': typeof AppWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/executions/$id': typeof AdminExecutionsIdRoute
  '/admin/missions/$id': typeof AdminMissionsIdRoute
  '/app/missions/$id': typeof AppMissionsIdRoute
  '/admin/executions/': typeof AdminExecutionsIndexRoute
  '/admin/missions/': typeof AdminMissionsIndexRoute
  '/app/missions/': typeof AppMissionsIndexRoute
  '/app/missions_/$id/execute': typeof AppMissionsIdExecuteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/admin/campaigns'
    | '/admin/executions'
    | '/admin/missions'
    | '/admin/participants'
    | '/admin/redemptions'
    | '/admin/rewards'
    | '/admin/venues'
    | '/app/activity'
    | '/app/missions'
    | '/app/profile'
    | '/app/rewards'
    | '/app/venues'
    | '/app/wallet'
    | '/admin/'
    | '/app/'
    | '/admin/executions/$id'
    | '/admin/missions/$id'
    | '/app/missions/$id'
    | '/admin/executions/'
    | '/admin/missions/'
    | '/app/missions/'
    | '/app/missions/$id/execute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/campaigns'
    | '/admin/participants'
    | '/admin/redemptions'
    | '/admin/rewards'
    | '/admin/venues'
    | '/app/activity'
    | '/app/profile'
    | '/app/rewards'
    | '/app/venues'
    | '/app/wallet'
    | '/admin'
    | '/app'
    | '/admin/executions/$id'
    | '/admin/missions/$id'
    | '/app/missions/$id'
    | '/admin/executions'
    | '/admin/missions'
    | '/app/missions'
    | '/app/missions/$id/execute'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/admin/campaigns'
    | '/admin/executions'
    | '/admin/missions'
    | '/admin/participants'
    | '/admin/redemptions'
    | '/admin/rewards'
    | '/admin/venues'
    | '/app/activity'
    | '/app/missions'
    | '/app/profile'
    | '/app/rewards'
    | '/app/venues'
    | '/app/wallet'
    | '/admin/'
    | '/app/'
    | '/admin/executions/$id'
    | '/admin/missions/$id'
    | '/app/missions/$id'
    | '/admin/executions/'
    | '/admin/missions/'
    | '/app/missions/'
    | '/app/missions_/$id/execute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/executions': {
      id: '/admin/executions'
      path: '/executions'
      fullPath: '/admin/executions'
      preLoaderRoute: typeof AdminExecutionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/missions': {
      id: '/admin/missions'
      path: '/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof AdminMissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redemptions': {
      id: '/admin/redemptions'
      path: '/redemptions'
      fullPath: '/admin/redemptions'
      preLoaderRoute: typeof AdminRedemptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/venues': {
      id: '/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missions': {
      id: '/app/missions'
      path: '/missions'
      fullPath: '/app/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rewards': {
      id: '/app/rewards'
      path: '/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/venues': {
      id: '/app/venues'
      path: '/venues'
      fullPath: '/app/venues'
      preLoaderRoute: typeof AppVenuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/executions/': {
      id: '/admin/executions/'
      path: '/'
      fullPath: '/admin/executions/'
      preLoaderRoute: typeof AdminExecutionsIndexRouteImport
      parentRoute: typeof AdminExecutionsRoute
    }
    '/admin/executions/$id': {
      id: '/admin/executions/$id'
      path: '/$id'
      fullPath: '/admin/executions/$id'
      preLoaderRoute: typeof AdminExecutionsIdRouteImport
      parentRoute: typeof AdminExecutionsRoute
    }
    '/admin/missions/': {
      id: '/admin/missions/'
      path: '/'
      fullPath: '/admin/missions/'
      preLoaderRoute: typeof AdminMissionsIndexRouteImport
      parentRoute: typeof AdminMissionsRoute
    }
    '/admin/missions/$id': {
      id: '/admin/missions/$id'
      path: '/$id'
      fullPath: '/admin/missions/$id'
      preLoaderRoute: typeof AdminMissionsIdRouteImport
      parentRoute: typeof AdminMissionsRoute
    }
    '/app/missions/': {
      id: '/app/missions/'
      path: '/'
      fullPath: '/app/missions/'
      preLoaderRoute: typeof AppMissionsIndexRouteImport
      parentRoute: typeof AppMissionsRoute
    }
    '/app/missions/$id': {
      id: '/app/missions/$id'
      path: '/$id'
      fullPath: '/app/missions/$id'
      preLoaderRoute: typeof AppMissionsIdRouteImport
      parentRoute: typeof AppMissionsRoute
    }
    '/app/missions_/$id/execute': {
      id: '/app/missions_/$id/execute'
      path: '/missions/$id/execute'
      fullPath: '/app/missions/$id/execute'
      preLoaderRoute: typeof AppMissionsIdExecuteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminExecutionsRouteChildren {
  AdminExecutionsIdRoute: typeof AdminExecutionsIdRoute
  AdminExecutionsIndexRoute: typeof AdminExecutionsIndexRoute
}

const AdminExecutionsRouteChildren: AdminExecutionsRouteChildren = {
  AdminExecutionsIdRoute: AdminExecutionsIdRoute,
  AdminExecutionsIndexRoute: AdminExecutionsIndexRoute,
}

const AdminExecutionsRouteWithChildren = AdminExecutionsRoute._addFileChildren(
  AdminExecutionsRouteChildren,
)

interface AdminMissionsRouteChildren {
  AdminMissionsIdRoute: typeof AdminMissionsIdRoute
  AdminMissionsIndexRoute: typeof AdminMissionsIndexRoute
}

const AdminMissionsRouteChildren: AdminMissionsRouteChildren = {
  AdminMissionsIdRoute: AdminMissionsIdRoute,
  AdminMissionsIndexRoute: AdminMissionsIndexRoute,
}

const AdminMissionsRouteWithChildren = AdminMissionsRoute._addFileChildren(
  AdminMissionsRouteChildren,
)

interface AdminRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminExecutionsRoute: typeof AdminExecutionsRouteWithChildren
  AdminMissionsRoute: typeof AdminMissionsRouteWithChildren
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminRedemptionsRoute: typeof AdminRedemptionsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminExecutionsRoute: AdminExecutionsRouteWithChildren,
  AdminMissionsRoute: AdminMissionsRouteWithChildren,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminRedemptionsRoute: AdminRedemptionsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminVenuesRoute: AdminVenuesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppMissionsRouteChildren {
  AppMissionsIdRoute: typeof AppMissionsIdRoute
  AppMissionsIndexRoute: typeof AppMissionsIndexRoute
}

const AppMissionsRouteChildren: AppMissionsRouteChildren = {
  AppMissionsIdRoute: AppMissionsIdRoute,
  AppMissionsIndexRoute: AppMissionsIndexRoute,
}

const AppMissionsRouteWithChildren = AppMissionsRoute._addFileChildren(
  AppMissionsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppMissionsRoute: typeof AppMissionsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppVenuesRoute: typeof AppVenuesRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMissionsIdExecuteRoute: typeof AppMissionsIdExecuteRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppMissionsRoute: AppMissionsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppVenuesRoute: AppVenuesRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppMissionsIdExecuteRoute: AppMissionsIdExecuteRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
